### ISSUE TITLE
What is the default IV (personalization) to blake2b function?

### ISSUE THREAD

**Issue by drewstone** [cesarb/blake2-rfc#14]
I'm looking for an 8-byte value such as one used in `sapling-crypto`: https://github.com/matter-labs/sapling-crypto/blob/master/src/circuit/blake2s.rs#L265

**Comment by cesarb** [comment]
The implementation of blake2b and blake2s in this crate follows RFC 7693, which doesn't have a personalization value. If you need one, you can use the undocumented `with_parameter_block` constructor, but you'll have to provide the full parameter block yourself.
