### ISSUE TITLE
Does not build with `simd` feature enabled

### ISSUE THREAD

**Issue by sanmai-NL** [cesarb/blake2-rfc#7]
`Cargo.toml`: 
```toml
[dependencies]
blake2 = { version = "*", features = ["simd"] }
```

rustc 1.24.0-nightly (f8af59d95 2017-12-13)

```
error[E0432]: unresolved import `simdint`
 --> /home/sanmai/.cargo/bin/registry/src/github.com-1ecc6299db9ec823/blake2-0.7.0/src/simd/simdop.rs:9:30
  |
9 | #[cfg(feature = "simd")] use simdint;
  |                              ^^^^^^^ no `simdint` in the root
```

**Comment by cesarb** [comment]
Sorry, but you're in the wrong repository. This one is for the `blake2-rfc` crate.

The `blake2` crate is at https://github.com/RustCrypto/hashes and, while it copied the blake2 code from this crate (with permission), both crates have since diverged.

**Comment by ghost** [comment]
> Sorry, but you're in the wrong repository. This one is for the `blake2-rfc` crate.
> 
> The `blake2` crate is at https://github.com/RustCrypto/hashes and, while it copied the blake2 code from this crate (with permission), both crates have since diverged.

This crate doesn't build with simd too: error: last argument of `simd_shuffle` is required to be a `const` item
