### ISSUE TITLE
Implement Copy on Blake2b?

### ISSUE THREAD

**Issue by sourcefrog** [cesarb/blake2-rfc#8]
It would sometimes be useful to copy the hash accumulator state.

**Comment by cesarb** [comment]
Implementing the Copy trait would risk accidentally duplicating the hash state. When you want to duplicate it explicitly, you can use the Clone trait, which is already implemented.

**Comment by sourcefrog** [comment]
You're quite right, I should have just used `.clone()`, thanks.
